version: '2'

services:
    app:
        image: 'status-io:latest'
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: status-io-app
        depends_on:
            - db
        environment:
              - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
              - SPRING_DATASOURCE_USERNAME=postgres
              - SPRING_DATASOURCE_PASSWORD=admin
              - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        volumes:
            - /Users/kaviarasu/DockerData:/app
        ports:
            - "8080:8080"

    db:
        image: 'postgres:13.1-alpine'
        container_name: status-io-db
        environment:
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432